---
- hosts: all
  gather_facts: no
  tasks:
    - name: Print Hello
      debug:
        msg: 'Hello from Ansible'
    - name: copy Dockerfile into Remote machine
      copy:
        src: Dockerfile
        dest: .

