---
- hosts: localhost
  tasks:
  - name: copy Dockerfile into Remote machine
    copy:
      src: Dockerfile
      dest: .
  - name: copy app.py into Remote machine
    copy:
      src: app.py
      dest: .
  - name: copy requirements.txt file into Remote machine
    copy:
      src: requirements.txt
      dest: .
  - name: Stop the running container
    command: sudo docker stop helloworld_container
    ignore_errors: True
  - name: remove the running container
    command: sudo docker rm helloworld_container
    ignore_errors: True
  - name: remove the running image
    command: sudo docker rmi helloworld_image
    ignore_errors: True
  - name: Create the image from Docker file
    command: sudo docker build -t helloworld_image .
  - name: Create and run container
    command: sudo docker run -d -p 5000:5000 --name helloworld_container helloworld_image

